### ISSUE TITLE
Accéder publiquement à Simulation Generator

### ISSUE THREAD

**Issue by benoit-dubreuil** [benoit-dubreuil/inm5803-ete2022#28]
## Description

Il est problématique de nécessiter des droits accordés manuellement en lecture au projet [Simulation Generator](https://bitbucket.org/voxsim/simulation_generator).

Si on veut que le projet de stage soit open source, alors il faut que le public ait accès aux dépendances.
De plus, cela rend l'intégration continue et son développement plus compliqués.

## To do

- [x] Demander à [Alex Valcourt Caron](alex.valcourt.caron@usherbrooke.ca) s'il peut rendre le projet ouvert au public.
- [x] Si le dépôt ne sera pas rendu public, alors trouver une alternative pour le rendre utilisable par le public, en accord avec l'auteur.

## References

- [benoit-dubreuil/inf6200-h2022/guides/outils.md](https://github.com/benoit-dubreuil/inf6200-h2022/blob/main/guides/outils.md)

## Dependencies

- None

**Comment by benoit-dubreuil** [comment]
Je viens tout juste d'envoyer un courriel à @AlexVCaron (Alex Valcourt Caron) pour rendre le dépôt public.

**Comment by benoit-dubreuil** [comment]
Mise à jour : @AlexVCaron prévoit forker le projet Simulation Generator sur GitHub à partir de Bitbucket.

**Comment by AlexVCaron** [comment]
Bonjour, la version publique du repo est maintenant accessible ici : https://github.com/AlexVCaron/voxsim

Je dois encore ajouter un document sur le code styling et la contribution, ça devrait être fait en début de semaine prochaine.

**Comment by benoit-dubreuil** [comment]
> Bonjour, la version publique du repo est maintenant accessible ici : https://github.com/AlexVCaron/voxsim
> 
> Je dois encore ajouter un document sur le code styling et la contribution, ça devrait être fait en début de semaine prochaine.

Merci beaucoup Alex! 😄
